name: DamageIndicator
main: cl.mastercode.DamageIndicator.Main
author: CristianDossow
version: ${project.version}
commands:
  damageindicator:
    description: Main DamageIndicator command
    usage: /<command> <arguments>
    aliases: [di, DamageIndicator]
permissions:
  damageindicator.admin:
    description: Access to admin commands